#!/bin/bash

# Daily News Update for follow-builders-digest
# This script is triggered by cron job system events

WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search"
DATE=$(date +%Y-%m-%d)
NEWS_FILE="$WORK_DIR/$DATE-news.md"

cd "$WORK_DIR"

echo "📰 Starting daily news update for $DATE..."

# Check if TAVILY_API_KEY is set - if not, set it from the known key
if [ -z "$TAVILY_API_KEY" ]; then
    echo "Setting TAVILY_API_KEY from known configuration..."
    export TAVILY_API_KEY="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"
fi

# Function to fetch news using Tavily skill
fetch_news_count() {
    local search_query="$1"
    
    local tmpfile=$(mktemp /tmp/news-XXXXXX.txt)
    
    # Use the tavily skill to fetch news
    node "$SCRIPT_DIR/scripts/search.mjs" "$search_query" --topic news --days 1 > "$tmpfile" 2>&1
    
    # Count articles
    if [ -s "$tmpfile" ]; then
        local count=$(grep -cE '^\- \*\*' "$tmpfile" || echo "0")
        rm -f "$tmpfile"
        echo "$count"
    else
        rm -f "$tmpfile"
        echo "0"
    fi
}

# Function to format news content
format_news_content() {
    local topic="$1"
    local section_title="$2"
    local search_query="$3"
    
    echo "🔍 Fetching $topic news..." >&2
    
    local tmpfile=$(mktemp /tmp/news-XXXXXX.txt)
    
    # Use the tavily skill to fetch news
    node "$SCRIPT_DIR/scripts/search.mjs" "$search_query" --topic news --days 1 > "$tmpfile" 2>&1
    
    # Process results
    if [ -s "$tmpfile" ]; then
        # Add section header
        echo "## 📰 $section_title"
        echo ""
        
        # Extract and format news articles from Tavily markdown output
        local processed_articles=0
        local in_sources=false
        local current_title=""
        local current_url=""

        while IFS= read -r line; do
            # Detect start of Sources section
            if [[ "$line" == "## Sources" ]]; then
                in_sources=true
                continue
            fi

            if [ "$in_sources" = true ] && [ "$processed_articles" -ge 5 ]; then
                break
            fi

            # Extract title from markdown bold: - **Title text**
            if [ "$in_sources" = true ]; then
                if [[ "$line" =~ ^-\ \*\*(.+)\*\* ]]; then
                    current_title="${BASH_REMATCH[1]}"
                    # Remove trailing "(relevance: XX%)" if present
                    current_title=$(echo "$current_title" | sed 's/ (relevance: [0-9]*%)$//')
                    # Remove any trailing URL in parentheses
                    current_title=$(echo "$current_title" | sed 's/ (https\?:[^)]*)$//')
                    echo "- **$current_title**"
                    current_url=""
                # Extract URL from the next line
                elif [[ -n "$current_title" && "$line" =~ https?:// ]]; then
                    current_url=$(echo "$line" | grep -oE 'https?://[^[:space:]]+' | head -1)
                    echo "  <$current_url>"
                    echo ""
                    processed_articles=$((processed_articles + 1))
                    current_title=""
                fi
            fi
        done < "$tmpfile"
    else
        echo "## 📰 $section_title"
        echo ""
        echo "*暂无新闻数据*"
    fi
    echo ""
    
    # Clean up
    rm -f "$tmpfile"
}

# Create news file for today
cat > "$NEWS_FILE" << EOF
---
layout: default
title: "新闻速递 — $DATE"
date: $DATE
---

# 📰 新闻速递 — $DATE

---

EOF

# Count articles for each category
international_count=$(fetch_news_count "今日国际新闻 全球要闻")
china_count=$(fetch_news_count "今日国内新闻 中国要闻")
tech_count=$(fetch_news_count "科技新闻 AI人工智能 财经要闻")

# Format news content (redirect function output to file)
format_news_content "international" "🌍 国际新闻" "今日国际新闻 全球要闻" >> "$NEWS_FILE"
echo "---" >> "$NEWS_FILE"

format_news_content "china" "🇨🇳 国内新闻" "今日国内新闻 中国要闻" >> "$NEWS_FILE"
echo "---" >> "$NEWS_FILE"

format_news_content "tech" "💼 财经科技" "科技新闻 AI人工智能 财经要闻" >> "$NEWS_FILE"
echo "---" >> "$NEWS_FILE"

# Calculate total articles
total_articles=$((international_count + china_count + tech_count))

# Add footer with statistics
cat >> "$NEWS_FILE" << EOF

## 📊 今日数据

**精选文章：$total_articles 篇**

- 🌍 国际: $international_count 篇
- 🇨🇳 国内: $china_count 篇
- 💼 科技: $tech_count 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y-%m-%d %H:%M')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
EOF

# Git operations
echo "📝 Committing changes to git..."
if git add "$NEWS_FILE" && git commit -m "📰 Update daily news for $DATE ($total_articles articles)"; then
    echo "✅ Changes committed successfully"
    if git push origin master; then
        echo "✅ Changes pushed to GitHub"
    else
        echo "⚠️ Push failed - manual intervention may be needed"
    fi
else
    echo "ℹ️ No changes to commit (file may already exist or no new news)"
fi

echo "✅ Daily news update completed for $DATE"