#!/bin/bash

# Daily News Update for follow-builders-digest
# This script is triggered by cron job system events

WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search"
DATE=$(date +%Y-%m-%d)
NEWS_FILE="$WORK_DIR/2026-$DATE-news.md"

cd "$WORK_DIR"

echo "📰 Starting daily news update for $DATE..."

# Check if TAVILY_API_KEY is set
if [ -z "$TAVILY_API_KEY" ]; then
    echo "❌ TAVILY_API_KEY environment variable not set"
    echo "Please configure TAVILY_API_KEY before running this script"
    exit 1
fi

# Function to fetch and format news
fetch_news() {
    local topic="$1"
    local section_title="$2"
    local search_query="$3"
    
    echo "🔍 Fetching $topic news..."
    
    # Use the tavily skill to fetch news
    if [ "$topic" = "international" ]; then
        node "$SCRIPT_DIR/scripts/search.mjs "$search_query" --topic news --days 1" > temp_news.txt
    elif [ "$topic" = "china" ]; then
        node "$SCRIPT_DIR/scripts/search.mjs "$search_query" --topic news --days 1" > temp_news.txt
    elif [ "$topic" = "tech" ]; then
        node "$SCRIPT_DIR/scripts/search.mjs "$search_query" --topic news --days 1" > temp_news.txt
    fi
    
    # Process results and count articles
    local article_count=0
    if [ -s temp_news.txt ]; then
        # Count articles (rough estimate)
        article_count=$(grep -c "Title:" temp_news.txt || echo "0")
    fi
    
    echo "## 📰 $section_title"
    echo ""
    
    if [ -s temp_news.txt ]; then
        # Extract and format news articles
        grep "Title:" temp_news.txt | head -10 | while read -r line; do
            title=$(echo "$line" | sed 's/Title: //')
            echo "- **$title**"
            
            # Find the corresponding URL (next line after Title)
            sed -n "/Title: $title/{n; p}" temp_news.txt | sed 's/URL: //'
            echo ""
        done
    else
        echo "*暂无新闻数据*"
    fi
    echo ""
    
    echo "$article_count"
}

# Create news file for today
cat > "$NEWS_FILE" << EOF
---
layout: default
title: "新闻速递 — 2026年$DATE"
date: $DATE
---

# 📰 新闻速递 — 2026年$DATE

---

EOF

# Fetch news for each category and count articles
international_count=$(fetch_news "international" "🌍 国际新闻" "world news latest breaking news")
echo "---" >> "$NEWS_FILE"

china_count=$(fetch_news "china" "🇨🇳 国内新闻" "China news latest breaking news")
echo "---" >> "$NEWS_FILE"

tech_count=$(fetch_news "tech" "💼 财经科技" "AI technology news latest tech news")
echo "---" >> "$NEWS_FILE"

# Calculate total articles
total_articles=$((international_count + china_count + tech_count))

# Add footer with statistics
cat >> "$NEWS_FILE" << EOF

## 📊 今日数据

**精选文章：$total_articles 篇**

- 🌍 国际: $international_count 篇
- 🇨🇳 国内: $china_count 篇
- 💼 科技: $tech_count 篇

---

*Generated by OpenClaw News Aggregator - $(date)*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
EOF

# Clean up temporary files
rm -f temp_news.txt

# Git operations
echo "📝 Committing changes to git..."
if git add "$NEWS_FILE" && git commit -m "📰 Update daily news for $DATE ($total_articles articles)"; then
    echo "✅ Changes committed successfully"
    if git push origin main; then
        echo "✅ Changes pushed to GitHub"
    else
        echo "⚠️ Push failed - manual intervention may be needed"
    fi
else
    echo "ℹ️ No changes to commit (file may already exist or no new news)"
fi

echo "✅ Daily news update completed for $DATE"