#!/bin/bash

# Daily News Fetcher using Tavily Search Skill
# Fetches international, domestic China, and tech news

set -e

# Configuration
TAVILY_SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search/scripts"
CURRENT_DATE=$(date +%Y-%m-%d)
NEWS_FILE="${CURRENT_DATE}-news.md"

echo "📰 Starting daily news fetch for ${CURRENT_DATE}"

# Change to work directory
cd "/Users/zx/.openclaw/workspace/follow-builders-digest"

# Check if Tavily API key is set
if [ -z "$TAVILY_API_KEY" ]; then
    echo "⚠️ Warning: TAVILY_API_KEY environment variable is not set"
    echo "Creating placeholder news file..."
    
    # Create placeholder news file
    cat > "${NEWS_FILE}" << EOF
---
layout: default
title: "新闻速递 — ${CURRENT_DATE}"
date: ${CURRENT_DATE}
---

# 📰 新闻速递 — ${CURRENT_DATE}

---

## 🌍 国际新闻

*暂无国际新闻数据 - TAVILY_API_KEY 未配置*

---

## 🇨🇳 国内新闻

*暂无国内新闻数据 - TAVILY_API_KEY 未配置*

---

## 💼 财经科技

*暂无科技新闻数据 - TAVILY_API_KEY 未配置*

---

## 📊 今日数据

**精选文章：0 篇**

- 🌍 国际: 0 篇
- 🇨🇳 国内: 0 篇
- 💼 科技: 0 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y/%m/%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
TAVILY_API_KEY 环境变量未配置，无法获取实时数据。

EOF
    
    echo "Placeholder news file created: ${NEWS_FILE}"
else
    echo "✅ TAVILY_API_KEY is set"
    
    # Check if Tavily script exists
    if [ ! -f "${TAVILY_SCRIPT_DIR}/search.mjs" ]; then
        echo "❌ Error: Tavily search script not found at ${TAVILY_SCRIPT_DIR}/search.mjs"
        exit 1
    fi
    
    # Fetch news using Tavily skill
    fetch_news() {
        local query="$1"
        local category="$2"
        local output_file="temp-${category}.md"
        
        echo "🔍 Fetching ${category} news..."
        
        # Use the tavily search script with news topic
        if node "${TAVILY_SCRIPT_DIR}/search.mjs" "${query}" --topic news --days 1 > "${output_file}"; then
            echo "✅ Successfully fetched ${category} news"
            return 0
        else
            echo "❌ Warning: Failed to fetch ${category} news"
            # Create empty file
            > "${output_file}"
            return 1
        fi
    }
    
    # Generate final news markdown
    generate_news_markdown() {
        local temp_file="temp-news-content.md"
        
        # Create the markdown file with front matter
        cat > "${temp_file}" << EOF
---
layout: default
title: "新闻速递 — ${CURRENT_DATE}"
date: ${CURRENT_DATE}
---

# 📰 新闻速递 — ${CURRENT_DATE}

---

EOF
        
        # International News
        echo "## 🌍 国际新闻" >> "${temp_file}"
        echo "" >> "${temp_file}"
        
        if [ -f "temp-international.md" ]; then
            # Clean up the international news content and format it
            sed '1,2d' "temp-international.md" >> "${temp_file}"
            echo "" >> "${temp_file}"
            echo "" >> "${temp_file}"
        else
            echo "  No international news available" >> "${temp_file}"
            echo "" >> "${temp_file}"
        fi
        
        # China Domestic News
        echo "## 🇨🇳 国内新闻" >> "${temp_file}"
        echo "" >> "${temp_file}"
        
        if [ -f "temp-china.md" ]; then
            # Clean up the china news content and format it
            sed '1,2d' "temp-china.md" >> "${temp_file}"
            echo "" >> "${temp_file}"
            echo "" >> "${temp_file}"
        else
            echo "  No domestic news available" >> "${temp_file}"
            echo "" >> "${temp_file}"
        fi
        
        # Tech/Finance News
        echo "## 💼 财经科技" >> "${temp_file}"
        echo "" >> "${temp_file}"
        
        if [ -f "temp-tech.md" ]; then
            # Clean up the tech news content and format it
            sed '1,2d' "temp-tech.md" >> "${temp_file}"
            echo "" >> "${temp_file}"
            echo "" >> "${temp_file}"
        else
            echo "  No tech news available" >> "${temp_file}"
            echo "" >> "${temp_file}"
        fi
        
        echo "" >> "${temp_file}"
        echo "" >> "${temp_file}"
        
        # Summary section - count news items
        local international_count=0
        local china_count=0
        local tech_count=0
        
        if [ -f "temp-international.md" ]; then
            international_count=$(grep -c '\*\*' "temp-international.md" 2>/dev/null || echo "0")
        fi
        
        if [ -f "temp-china.md" ]; then
            china_count=$(grep -c '\*\*' "temp-china.md" 2>/dev/null || echo "0")
        fi
        
        if [ -f "temp-tech.md" ]; then
            tech_count=$(grep -c '\*\*' "temp-tech.md" 2>/dev/null || echo "0")
        fi
        
        local total_count=$((international_count + china_count + tech_count))
        
        cat >> "${temp_file}" << EOF
## 📊 今日数据

**精选文章：${total_count} 篇**

- 🌍 国际: ${international_count} 篇
- 🇨🇳 国内: ${china_count} 篇
- 💼 科技: ${tech_count} 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y/%m/%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。

EOF
    }
    
    # Fetch all categories
    fetch_news "world news international breaking news today" "international"
    fetch_news "China news domestic news today 中国新闻" "china"
    fetch_news "AI technology news tech artificial intelligence 科技新闻 人工智能" "tech"
    
    # Generate markdown
    generate_news_markdown
    
    # Move the generated file to the final location
    if [ -f "temp-news-content.md" ]; then
        mv "temp-news-content.md" "${NEWS_FILE}"
        echo "✅ News file generated: ${NEWS_FILE}"
    else
        echo "❌ Error: Failed to generate news file"
        exit 1
    fi
    
    # Cleanup temp files
    rm -f temp-international.md temp-china.md temp-tech.md temp-news-content.md
fi

# Git operations
echo "📝 Committing changes to git..."
if git add "${NEWS_FILE}"; then
    # Commit
    commit_message="📰 Update daily news for ${CURRENT_DATE}"
    if git commit -m "${commit_message}"; then
        # Push
        if git push origin master; then
            echo "✅ Changes committed and pushed successfully"
        else
            echo "⚠️ Git push failed"
        fi
    else
        echo "⚠️ Git commit failed"
    fi
else
    echo "⚠️ Git add failed"
fi

echo "✅ Daily news fetch completed for ${CURRENT_DATE}"