#!/bin/bash

# Daily News Update for follow-builders-digest
# This script is triggered by cron job system events

WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search"
DATE=$(date +%Y-%m-%d)
NEWS_FILE="$WORK_DIR/$DATE-news.md"

cd "$WORK_DIR"

echo "📰 Starting daily news update for $DATE..."

# Check if TAVILY_API_KEY is set - if not, set it from the known key
if [ -z "$TAVILY_API_KEY" ]; then
    echo "Setting TAVILY_API_KEY from known configuration..."
    export TAVILY_API_KEY="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"
fi

# Function to fetch news using Tavily skill
fetch_and_format_news() {
    local topic="$1"
    local section_title="$2"
    local search_query="$3"
    
    echo "🔍 Fetching $topic news..."
    
    # Use the tavily skill to fetch news
    node "$SCRIPT_DIR/scripts/search.mjs" "$search_query" --topic news --days 1 > temp_news.txt 2>&1
    
    # Process results
    if [ -s temp_news.txt ]; then
        # Count articles (rough estimate)
        local article_count=$(grep -c "Title:" temp_news.txt || echo "0")
        
        # Add section header
        echo "## 📰 $section_title"
        echo ""
        
        # Extract and format news articles
        local processed_articles=0
        grep "Title:" temp_news.txt | head -8 | while read -r line; do
            if [ $processed_articles -ge 5 ]; then
                break
            fi
            
            title=$(echo "$line" | sed 's/Title: //')
            echo "- **$title**"
            
            # Find the corresponding URL (next line after Title)
            url_line=$(sed -n "/Title: $title/{n; p}" temp_news.txt | sed 's/URL: //')
            if [[ "$url_line" == http* ]]; then
                echo "  $url_line"
                echo ""
            fi
            
            ((processed_articles++))
        done
        
        # Clean up
        rm -f temp_news.txt
        
        echo "$article_count"
    else
        echo "## 📰 $section_title"
        echo ""
        echo "*暂无新闻数据*"
        echo ""
        echo "0"
    fi
}

# Create news file for today
cat > "$NEWS_FILE" << EOF
---
layout: default
title: "新闻速递 — $DATE"
date: $DATE
---

# 📰 新闻速递 — $DATE

---

EOF

# Fetch news for each category
international_count=$(fetch_and_format_news "international" "🌍 国际新闻" "今日国际新闻 全球要闻")
echo "---" >> "$NEWS_FILE"

china_count=$(fetch_and_format_news "china" "🇨🇳 国内新闻" "今日国内新闻 中国要闻")
echo "---" >> "$NEWS_FILE"

tech_count=$(fetch_and_format_news "tech" "💼 财经科技" "科技新闻 AI人工智能 财经要闻")
echo "---" >> "$NEWS_FILE"

# Calculate total articles
total_articles=$((international_count + china_count + tech_count))

# Add footer with statistics
cat >> "$NEWS_FILE" << EOF

## 📊 今日数据

**精选文章：$total_articles 篇**

- 🌍 国际: $international_count 篇
- 🇨🇳 国内: $china_count 篇
- 💼 科技: $tech_count 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y-%m-%d %H:%M')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
EOF

# Clean up temporary files
rm -f temp_news.txt

# Git operations
echo "📝 Committing changes to git..."
if git add "$NEWS_FILE" && git commit -m "📰 Update daily news for $DATE ($total_articles articles)"; then
    echo "✅ Changes committed successfully"
    if git push origin master; then
        echo "✅ Changes pushed to GitHub"
    else
        echo "⚠️ Push failed - manual intervention may be needed"
    fi
else
    echo "ℹ️ No changes to commit (file may already exist or no new news)"
fi

echo "✅ Daily news update completed for $DATE"