#!/bin/bash

# Daily News Fetcher using Tavily API
# Fetches international, domestic China, and tech news

set -e

# Configuration
TAVILY_API_KEY="${TAVILY_API_KEY}"
CURRENT_DATE=$(date +%Y-%m-%d)
NEWS_FILE="${CURRENT_DATE}-news.md"
TEMP_DIR=$(mktemp -d)

# Check if Tavily API key is set
if [ -z "$TAVILY_API_KEY" ]; then
    echo "Error: TAVILY_API_KEY environment variable is not set"
    exit 1
fi

# Fetch news using Tavily API
fetch_news() {
    local query="$1"
    local category="$2"
    local output_file="${TEMP_DIR}/${category}.json"
    
    echo "Fetching ${category} news..."
    
    curl -s "https://api.tavily.com/search" \
        -H "Content-Type: application/json" \
        -d "{
            \"api_key\": \"${TAVILY_API_KEY}\",
            \"query\": \"${query}\",
            \"max_results\": 10,
            \"search_depth\": \"advanced\",
            \"include_domains\": [],
            \"exclude_domains\": []
        }" > "${output_file}"
    
    if [ $? -ne 0 ] || [ ! -s "${output_file}" ]; then
        echo "Warning: Failed to fetch ${category} news"
        return 1
    fi
    
    echo "Successfully fetched ${category} news"
    return 0
}

# Process news results and generate markdown
generate_news_markdown() {
    local temp_file="${TEMP_DIR}/news-content.md"
    
    # Create the markdown file with front matter
    cat > "${temp_file}" << EOF
---
layout: default
title: "新闻速递 — ${CURRENT_DATE}"
date: ${CURRENT_DATE}
---

# 📰 新闻速递 — ${CURRENT_DATE}

---

EOF
    
    # International News
    echo "## 🌍 国际新闻" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    if [ -f "${TEMP_DIR}/international.json" ]; then
        jq -r '.results[] | "- **\(.title | gsub("\\\\"; "") | gsub("\""; "")) - \(.source) (relevance: \(.relevance | floor))%**\n  <\(.url)>"' "${TEMP_DIR}/international.json" 2>/dev/null | while IFS= read -r line; do
            if [ -n "$line" ]; then
                echo "  $line" >> "${temp_file}"
            fi
        done
    else
        echo "  No international news available" >> "${temp_file}"
    fi
    
    echo "" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    # China Domestic News
    echo "## 🇨🇳 国内新闻" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    if [ -f "${TEMP_DIR}/china.json" ]; then
        jq -r '.results[] | "- **\(.title | gsub("\\\\"; "") | gsub("\""; "")) - \(.source) (relevance: \(.relevance | floor))%**\n  <\(.url)>"' "${TEMP_DIR}/china.json" 2>/dev/null | while IFS= read -r line; do
            if [ -n "$line" ]; then
                echo "  $line" >> "${temp_file}"
            fi
        done
    else
        echo "  No domestic news available" >> "${temp_file}"
    fi
    
    echo "" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    # Tech/Finance News
    echo "## 💼 财经科技" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    if [ -f "${TEMP_DIR}/tech.json" ]; then
        jq -r '.results[] | "- **\(.title | gsub("\\\\"; "") | gsub("\""; "")) - \(.source) (relevance: \(.relevance | floor))%**\n  <\(.url)>"' "${TEMP_DIR}/tech.json" 2>/dev/null | while IFS= read -r line; do
            if [ -n "$line" ]; then
                echo "  $line" >> "${temp_file}"
            fi
        done
    else
        echo "  No tech news available" >> "${temp_file}"
    fi
    
    echo "" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    # Summary section
    local international_count=0
    local china_count=0
    local tech_count=0
    
    if [ -f "${TEMP_DIR}/international.json" ]; then
        international_count=$(jq '.results | length' "${TEMP_DIR}/international.json" 2>/dev/null || echo "0")
    fi
    
    if [ -f "${TEMP_DIR}/china.json" ]; then
        china_count=$(jq '.results | length' "${TEMP_DIR}/china.json" 2>/dev/null || echo "0")
    fi
    
    if [ -f "${TEMP_DIR}/tech.json" ]; then
        tech_count=$(jq '.results | length' "${TEMP_DIR}/tech.json" 2>/dev/null || echo "0")
    fi
    
    local total_count=$((international_count + china_count + tech_count))
    
    cat >> "${temp_file}" << EOF
## 📊 今日数据

**精选文章：${total_count} 篇**

- 🌍 国际: ${international_count} 篇
- 🇨🇳 国内: ${china_count} 篇
- 💼 科技: ${tech_count} 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y/%m/%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。

EOF
}

# Main execution
echo "Starting daily news fetch for ${CURRENT_DATE}"

# Fetch all categories
fetch_news "world news international" "international"
fetch_news "China news domestic Chinese" "china" 
fetch_news "AI technology tech innovation startup" "tech"

# Generate markdown
generate_news_markdown

# Move the generated file to the final location
if [ -f "${temp_file}" ]; then
    mv "${temp_file}" "${NEWS_FILE}"
    echo "News file generated: ${NEWS_FILE}"
else
    echo "Error: Failed to generate news file"
    exit 1
fi

# Cleanup
rm -rf "${TEMP_DIR}"

echo "Daily news fetch completed successfully!"