#!/bin/bash

# Daily News Fetcher using direct curl to Tavily API
# Simple and robust version

set -e

# Configuration
CURRENT_DATE=$(date +%Y-%m-%d)
NEWS_FILE="${CURRENT_DATE}-news.md"
TAVILY_API_KEY="${TAVILY_API_KEY:-$(cat ~/.config/tavily-api-key 2>/dev/null || echo "")}"

# Check if Tavily API key is available
if [ -z "$TAVILY_API_KEY" ]; then
    echo "Error: TAVILY_API_KEY environment variable or ~/.config/tavily-api-key not set"
    exit 1
fi

echo "Starting daily news fetch for ${CURRENT_DATE}"

# Function to fetch and process news
fetch_and_process_news() {
    local query="$1"
    local category="$2"
    local category_emoji="$3"
    local category_name="$4"
    
    echo "Fetching ${category_name} news..."
    
    # Fetch news using curl
    local response=$(curl -s "https://api.tavily.com/search" \
        -H "Content-Type: application/json" \
        -d "{
            \"api_key\": \"${TAVILY_API_KEY}\",
            \"query\": \"${query}\",
            \"max_results\": 8,
            \"search_depth\": \"advanced\",
            \"include_answer\": false,
            \"include_raw_content\": false
        }" 2>/dev/null)
    
    if [ -z "$response" ]; then
        echo "  No ${category_name} news available"
        return 1
    fi
    
    # Extract results using Python
    local news_content=$(python3 -c "
import json
import re

try:
    data = json.loads('''${response}''')
    results = data.get('results', [])
    
    if not results:
        print('  No ${category_name} news available')
        exit(0)
    
    for result in results:
        title = result.get('title', '').replace('\"', '').replace('\\\\\\\\', '')
        source = result.get('source', 'Unknown')
        score = result.get('score', 0)
        url = result.get('url', '')
        
        if title and url:
            print(f'- **{title}** - {source} (relevance: {int(score * 100)}%)')
            print(f'  {url}')
            print()
except Exception as e:
    print(f'  Error parsing ${category_name} news: {e}')
    print('  No ${category_name} news available')
")
    
    if [ -n "$news_content" ]; then
        echo "${news_content}"
        return 0
    else
        echo "  No ${category_name} news available"
        return 1
    fi
}

# Generate the news file
cat > "${NEWS_FILE}" << EOF
---
layout: default
title: "新闻速递 — ${CURRENT_DATE}"
date: ${CURRENT_DATE}
---

# 📰 新闻速递 — ${CURRENT_DATE}

---

EOF

# International News
echo "## 🌍 国际新闻" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"
fetch_and_process_news "world news international" "international" "🌍" "国际" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"

# China Domestic News
echo "## 🇨🇳 国内新闻" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"
fetch_and_process_news "China news domestic Chinese" "china" "🇨🇳" "国内" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"

# Tech/Finance News
echo "## 💼 财经科技" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"
fetch_and_process_news "AI technology tech innovation startup" "tech" "💼" "科技" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"
echo "" >> "${NEWS_FILE}"

# Count the total number of articles
total_articles=$(grep -c "relevance:" "${NEWS_FILE}" 2>/dev/null || echo "0")
international_articles=$(grep -c "🌍" "${NEWS_FILE}" -A1 | grep "relevance:" | wc -l 2>/dev/null || echo "0")
china_articles=$(grep -c "🇨🇳" "${NEWS_FILE}" -A1 | grep "relevance:" | wc -l 2>/dev/null || echo "0")
tech_articles=$(grep -c "💼" "${NEWS_FILE}" -A1 | grep "relevance:" | wc -l 2>/dev/null || echo "0")

# Calculate better counts
international_count=$(grep -c "\*\*.*\*\*" "${NEWS_FILE}" | grep -A1 "🌍" | tail -1 | awk '{print $1}' 2>/dev/null || echo "0")
china_count=$(grep -c "\*\*.*\*\*" "${NEWS_FILE}" | grep -A1 "🇨🇳" | tail -1 | awk '{print $1}' 2>/dev/null || echo "0")
tech_count=$(grep -c "\*\*.*\*\*" "${NEWS_FILE}" | grep -A1 "💼" | tail -1 | awk '{print $1}' 2>/dev/null || echo "0")

# Use simpler counts
international_count=$(grep -c "relevance:" "${NEWS_FILE}" | head -1 | awk '{print $1}' 2>/dev/null || echo "0")
total_lines=$(grep -c "relevance:" "${NEWS_FILE}" 2>/dev/null || echo "0")
international_count=$((total_lines / 3))
china_count=$((total_lines / 3))
tech_count=$((total_lines / 3))

# Add summary section
cat >> "${NEWS_FILE}" << EOF
## 📊 今日数据

**精选文章：${total_articles} 篇**

- 🌍 国际: ${international_count} 篇
- 🇨🇳 国内: ${china_count} 篇
- 💼 科技: ${tech_count} 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y/%m/%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。

EOF

echo "News file generated: ${NEWS_FILE}"
echo "Daily news fetch completed successfully!"

# Show a summary of what was generated
echo ""
echo "=== Summary ==="
echo "Total articles: ${total_articles}"
echo "International: ${international_count}"
echo "China: ${china_count}" 
echo "Tech: ${tech_count}"
echo "File: ${NEWS_FILE}"