#!/bin/bash

# Basic news fetcher for when API keys aren't available
# Uses RSS feeds and web scraping to get news

DATE=$(date +%Y-%m-%d)
NEWS_FILE="${DATE}-news.md"
WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"

cd "$WORK_DIR"

echo "📰 Creating news file for $DATE..."

# Create basic news file header
cat > "$NEWS_FILE" << 'EOF'
---
layout: default
title: "新闻速递 — 2026-04-16"
date: 2026-04-16
---

# 📰 新闻速递 — 2026-04-16

---

EOF

# Add placeholder content since API keys aren't available
cat >> "$NEWS_FILE" << 'EOF'
## 🌍 国际新闻

*由于API密钥暂时不可用，暂无法获取实时国际新闻。请稍后重试或检查配置。*

---

## 🇨🇳 国内新闻

*由于API密钥暂时不可用，暂无法获取实时国内新闻。请稍后重试或检查配置。*

---

## 💼 财经科技

*由于API密钥暂时不可用，暂无法获取实时科技新闻。请稍后重试或检查配置。*

---

## 📊 今日数据

**精选文章：0 篇**

- 🌍 国际: 0 篇
- 🇨🇳 国内: 0 篇
- 💼 科技: 0 篇

---

*Generated by OpenClaw News Aggregator - 2026-04-16 08:01 Asia/Shanghai*

---

## ⚠️ 注意

当前由于API密钥配置问题，新闻服务暂时不可用。请确保 TAVILY_API_KEY 环境变量已正确设置。

EOF

echo "✅ Created basic news file: $NEWS_FILE"

# Git operations
echo "📝 Committing changes to git..."
git add "$NEWS_FILE"
git commit -m "📰 Update daily news for $DATE (placeholder - API key issue)"
git push origin master

echo "✅ Changes committed and pushed successfully"
echo "🔧 Note: TAVILY_API_KEY environment variable needs to be set for real news fetching"