#!/bin/bash

# Daily News Fetcher using Tavily Search Skill
# Fetches international, domestic China, and tech news

set -e

# Configuration
TAVILY_SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search/scripts"
CURRENT_DATE=$(date +%Y-%m-%d)
NEWS_FILE="${CURRENT_DATE}-news.md"
TEMP_DIR=$(mktemp -d)

# Check if Tavily API key is set
if [ -z "$TAVILY_API_KEY" ]; then
    echo "Error: TAVILY_API_KEY environment variable is not set"
    exit 1
fi

# Check if Tavily script exists
if [ ! -f "${TAVILY_SCRIPT_DIR}/search.mjs" ]; then
    echo "Error: Tavily search script not found at ${TAVILY_SCRIPT_DIR}/search.mjs"
    exit 1
fi

# Fetch news using Tavily skill
fetch_news() {
    local query="$1"
    local category="$2"
    local output_file="${TEMP_DIR}/${category}.md"
    
    echo "Fetching ${category} news..."
    
    # Use the tavily search script with news topic
    if node "${TAVILY_SCRIPT_DIR}/search.mjs" "${query}" --topic news --days 1 > "${output_file}"; then
        echo "Successfully fetched ${category} news"
        return 0
    else
        echo "Warning: Failed to fetch ${category} news"
        return 1
    fi
}

# Generate final news markdown
generate_news_markdown() {
    local temp_file="${TEMP_DIR}/news-content.md"
    
    # Create the markdown file with front matter
    cat > "${temp_file}" << EOF
---
layout: default
title: "新闻速递 — ${CURRENT_DATE}"
date: ${CURRENT_DATE}
---

# 📰 新闻速递 — ${CURRENT_DATE}

---

EOF
    
    # International News
    echo "## 🌍 国际新闻" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    if [ -f "${TEMP_DIR}/international.md" ]; then
        # Clean up the international news content and format it
        sed '1,2d' "${TEMP_DIR}/international.md" >> "${temp_file}"
    else
        echo "  No international news available" >> "${temp_file}"
    fi
    
    echo "" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    # China Domestic News
    echo "## 🇨🇳 国内新闻" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    if [ -f "${TEMP_DIR}/china.md" ]; then
        # Clean up the china news content and format it
        sed '1,2d' "${TEMP_DIR}/china.md" >> "${temp_file}"
    else
        echo "  No domestic news available" >> "${temp_file}"
    fi
    
    echo "" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    # Tech/Finance News
    echo "## 💼 财经科技" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    if [ -f "${TEMP_DIR}/tech.md" ]; then
        # Clean up the tech news content and format it
        sed '1,2d' "${TEMP_DIR}/tech.md" >> "${temp_file}"
    else
        echo "  No tech news available" >> "${temp_file}"
    fi
    
    echo "" >> "${temp_file}"
    echo "" >> "${temp_file}"
    
    # Summary section - count news items
    local international_count=0
    local china_count=0
    local tech_count=0
    
    if [ -f "${TEMP_DIR}/international.md" ]; then
        international_count=$(grep -c '\*\*' "${TEMP_DIR}/international.md}" 2>/dev/null || echo "0")
    fi
    
    if [ -f "${TEMP_DIR}/china.md" ]; then
        china_count=$(grep -c '\*\*' "${TEMP_DIR}/china.md}" 2>/dev/null || echo "0")
    fi
    
    if [ -f "${TEMP_DIR}/tech.md" ]; then
        tech_count=$(grep -c '\*\*' "${TEMP_DIR}/tech.md}" 2>/dev/null || echo "0")
    fi
    
    local total_count=$((international_count + china_count + tech_count))
    
    cat >> "${temp_file}" << EOF
## 📊 今日数据

**精选文章：${total_count} 篇**

- 🌍 国际: ${international_count} 篇
- 🇨🇳 国内: ${china_count} 篇
- 💼 科技: ${tech_count} 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y/%m/%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。

EOF
}

# Main execution
echo "Starting daily news fetch for ${CURRENT_DATE}"

# Fetch all categories
fetch_news "world news international" "international"
fetch_news "China news domestic Chinese" "china"
fetch_news "AI technology tech innovation startup" "tech"

# Generate markdown
generate_news_markdown

# Move the generated file to the final location
if [ -f "${temp_file}" ]; then
    mv "${temp_file}" "${NEWS_FILE}"
    echo "News file generated: ${NEWS_FILE}"
else
    echo "Error: Failed to generate news file"
    exit 1
fi

# Cleanup
rm -rf "${TEMP_DIR}"

echo "Daily news fetch completed successfully!"