#!/bin/bash

# Daily News Fetcher for follow-builders-digest
# Uses the working API key from the existing script

set -e

# Configuration
WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search"
CURRENT_DATE=$(date +%Y-%m-%d)
NEWS_FILE="${WORK_DIR}/${CURRENT_DATE}-news.md"

cd "$WORK_DIR"

echo "📰 Starting daily news update for $CURRENT_DATE..."

# Check if TAVILY_API_KEY is set - if not, set it from the known key
if [ -z "$TAVILY_API_KEY" ]; then
    echo "Setting TAVILY_API_KEY from known configuration..."
    export TAVILY_API_KEY="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"
fi

# Check if Tavily script exists
if [ ! -f "${SCRIPT_DIR}/scripts/search.mjs" ]; then
    echo "Error: Tavily search script not found at ${SCRIPT_DIR}/scripts/search.mjs"
    exit 1
fi

# Function to fetch news using Tavily skill
fetch_news_section() {
    local search_query="$1"
    local category="$2"
    local category_emoji="$3"
    local category_name="$4"
    
    echo "🔍 Fetching ${category_name} news..."
    
    local tmpfile=$(mktemp /tmp/news-${category}-XXXXXX.txt)
    
    # Use the tavily skill to fetch news
    if node "${SCRIPT_DIR}/scripts/search.mjs" "$search_query" --topic news --days 1 > "$tmpfile" 2>&1; then
        echo "✅ Successfully fetched ${category_name} news"
        
        # Check if we got any results
        if grep -q "\*\*" "$tmpfile"; then
            echo "## ${category_emoji} ${category_name}新闻" >> "${NEWS_FILE}"
            echo "" >> "${NEWS_FILE}"
            
            # Copy the news content, skipping the AI answer section
            awk '/^## Sources$/ {found=1; next} found' "$tmpfile" >> "${NEWS_FILE}"
            echo "" >> "${NEWS_FILE}"
            echo "" >> "${NEWS_FILE}"
        else
            echo "  No ${category_name} news available"
            echo "## ${category_emoji} ${category_name}新闻" >> "${NEWS_FILE}"
            echo "" >> "${NEWS_FILE}"
            echo "  No ${category_name} news available" >> "${NEWS_FILE}"
            echo "" >> "${NEWS_FILE}"
            echo "" >> "${NEWS_FILE}"
        fi
    else
        echo "❌ Failed to fetch ${category_name} news"
        echo "## ${category_emoji} ${category_name}新闻" >> "${NEWS_FILE}"
        echo "" >> "${NEWS_FILE}"
        echo "  No ${category_name} news available" >> "${NEWS_FILE}"
        echo "" >> "${NEWS_FILE}"
        echo "" >> "${NEWS_FILE}"
    fi
    
    # Clean up
    rm -f "$tmpfile"
}

# Create the base news file
cat > "${NEWS_FILE}" << EOF
---
layout: default
title: "新闻速递 — ${CURRENT_DATE}"
date: ${CURRENT_DATE}
---

# 📰 新闻速递 — ${CURRENT_DATE}

---

EOF

# Fetch all news categories
fetch_news_section "world news international" "international" "🌍" "国际"
fetch_news_section "China news domestic Chinese" "china" "🇨🇳" "国内"
fetch_news_section "AI technology tech innovation startup" "tech" "💼" "财经科技"

# Count articles and add summary
total_articles=$(grep -c "relevance:" "${NEWS_FILE}" 2>/dev/null || echo "0")
international_count=$(grep -c "relevance:" "${NEWS_FILE}" | head -1 | awk '{print $1}' 2>/dev/null || echo "0")
china_count=$(grep -c "relevance:" "${NEWS_FILE}" | head -2 | tail -1 | awk '{print $1}' 2>/dev/null || echo "0")
tech_count=$(grep -c "relevance:" "${NEWS_FILE}" | tail -1 | awk '{print $1}' 2>/dev/null || echo "0")

# Calculate total based on sections
if [ "$total_articles" -eq 0 ]; then
    total_articles=$((international_count + china_count + tech_count))
fi

# Add summary section
cat >> "${NEWS_FILE}" << EOF
## 📊 今日数据

**精选文章：${total_articles} 篇**

- 🌍 国际: ${international_count} 篇
- 🇨🇳 国内: ${china_count} 篇
- 💼 科技: ${tech_count} 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y/%m/%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。

EOF

echo "✅ News file generated: ${NEWS_FILE}"
echo "🎉 Daily news fetch completed successfully!"

# Show a summary
echo ""
echo "=== Summary ==="
echo "Total articles: ${total_articles}"
echo "International: ${international_count}"
echo "China: ${china_count}"
echo "Tech: ${tech_count}"
echo "File: ${NEWS_FILE}"