#!/bin/bash

# Improved Daily News Update for follow-builders-digest
# Uses web_search tool directly for better reliability and formatting
# This script is triggered by cron job system events

WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
DATE=$(date +%Y-%m-%d)
NEWS_FILE="$WORK_DIR/$DATE-news.md"

# Check if tavily search script is available
TAVILY_SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search/scripts/search.mjs"
if [ ! -f "$TAVILY_SCRIPT_DIR" ]; then
    echo "❌ Tavily search script not found at $TAVILY_SCRIPT_DIR"
    exit 1
fi

cd "$WORK_DIR"

echo "📰 Starting improved daily news update for $DATE..."

# Check if TAVILY_API_KEY is set
if [ -z "$TAVILY_API_KEY" ]; then
    echo "⚠️ TAVILY_API_KEY not set. Using fallback API key..."
    export TAVILY_API_KEY="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"
fi

# Function to search news and extract titles
search_news() {
    local query="$1"
    local count="$2"
    
    echo "🔍 Searching for: $query" >&2
    
    # Use tavily search script
    local temp_file=$(mktemp /tmp/search-result-XXXXXX.txt)
    if node "$TAVILY_SCRIPT_DIR" "$query" --topic news --days 1 -n "$count" > "$temp_file" 2>&1; then
        local search_result=$(cat "$temp_file")
        if [ -n "$search_result" ] && [[ "$search_result" != *"Missing TAVILY_API_KEY"* ]]; then
            cat "$temp_file"
            rm -f "$temp_file"
            return 0
        fi
    fi
    
    echo "⚠️ Failed to fetch news for query: $query" >&2
    rm -f "$temp_file"
    return 1
    
    # Extract titles and URLs from search result
    echo "$search_result" | grep -E '^\- \*\*.+?\*\* \(relevance:' | while read -r line; do
        # Extract title from pattern: - **Title** (relevance: XX%)
        if [[ "$line" =~ ^-\ \*\*([^*]+)\*\* ]]; then
            title="${BASH_REMATCH[1]}"
            # Clean up title
            title=$(echo "$title" | sed 's/ *$//')
            echo "- **$title**"
            
            # Look for URL in the next line
            read -r url_line
            if [[ "$url_line" =~ https?:// ]]; then
                url=$(echo "$url_line" | grep -oE 'https?://[^[:space:]]+' | head -1)
                echo "  <$url>"
            fi
            echo ""
        fi
    done
    
    return 0
}

# Function to create news file with formatted content
create_news_file() {
    local international_content
    local china_content  
    local tech_content
    
    # Fetch international news
    echo "🌍 Fetching international news..." >&2
    international_content=$(echo "## 🌍 国际新闻

$(search_news "world news international breaking news global events" 8)")
    
    # Fetch China news
    echo "🇨🇳 Fetching China news..." >&2
    china_content=$(echo "## 🇨🇳 国内新闻

$(search_news "China news Chinese politics economy technology domestic news" 8)")
    
    # Fetch tech/ai news
    echo "💼 Fetching tech/ai news..." >&2
    tech_content=$(echo "## 💼 财经科技

$(search_news "AI artificial intelligence technology innovation startups venture capital" 8)")

    # Count articles
    international_count=$(echo "$international_content" | grep -c '^- \*\*' || echo "0")
    china_count=$(echo "$china_content" | grep -c '^- \*\*' || echo "0")
    tech_count=$(echo "$tech_content" | grep -c '^- \*\*' || echo "0")
    total_articles=$((international_count + china_count + tech_count))

    # Create the news file
    cat > "$NEWS_FILE" << EOF
---
layout: default
title: "新闻速递 — $DATE"
date: $DATE
---

# 📰 新闻速递 — $DATE

---

$international_content
---
$china_content
---
$tech_content
---

## 📊 今日数据

**精选文章：$total_articles 篇**

- 🌍 国际: $international_count 篇
- 🇨🇳 国内: $china_count 篇
- 💼 科技: $tech_count 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y-%m-%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
EOF
}

# Check if news file already exists and has recent content
if [ -f "$NEWS_FILE" ]; then
    file_age=$(( $(date +%s) - $(stat -f "%m" "$NEWS_FILE" 2>/dev/null || stat -c "%Y" "$NEWS_FILE" 2>/dev/null) ))
    
    # If file is less than 1 hour old, skip update
    if [ "$file_age" -lt 3600 ]; then
        echo "ℹ️ News file is recent (less than 1 hour old), skipping update"
        exit 0
    fi
fi

# Create the news file
create_news_file

echo "✅ News file created: $NEWS_FILE"

# Git operations
echo "📝 Committing changes to git..."

# Check if there are changes to commit
if git diff --quiet "$NEWS_FILE" 2>/dev/null; then
    echo "ℹ️ No changes to commit"
    exit 0
fi

# Stage and commit (use relative path)
if git add "$NEWS_FILE" && git commit -m "📰 Update daily news for $DATE ($total_articles articles)"; then
    echo "✅ Changes committed successfully"
    
    # Push to remote
    if git push origin master 2>/dev/null; then
        echo "✅ Changes pushed to GitHub"
    else
        echo "⚠️ Push failed - manual intervention may be needed"
        # Check if remote tracking branch exists
        if git ls-remote --heads origin master >/dev/null 2>&1; then
            echo "💡 Tip: Run 'git push origin master' manually"
        else
            echo "💡 Tip: Remote branch 'master' may not exist, check your remote setup"
        fi
    fi
else
    echo "❌ Failed to commit changes"
    exit 1
fi

echo "✅ Improved daily news update completed for $DATE"