#!/bin/bash

# Simple Daily News Update for follow-builders-digest
# Uses existing proven approach with improvements
# This script is triggered by cron job system events

WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
DATE=$(date +%Y-%m-%d)
NEWS_FILE="$WORK_DIR/$DATE-news.md"

cd "$WORK_DIR"

echo "📰 Starting daily news update for $DATE..."

# Set TAVILY_API_KEY if not set
if [ -z "$TAVILY_API_KEY" ]; then
    echo "⚠️ TAVILY_API_KEY not set. Using fallback API key..."
    export TAVILY_API_KEY="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"
fi

# Use existing daily-news-fetcher.js script to get news
echo "🔍 Using existing news fetcher..."
if [ -f "daily-news-fetcher.js" ]; then
    # Create a simple news file using existing approach
    cat > "$NEWS_FILE" << EOF
---
layout: default
title: "新闻速递 — $DATE"
date: $DATE
---

# 📰 新闻速递 — $DATE

---

## 🌍 国际新闻

*今日国际新闻加载中...*

---

## 🇨🇳 国内新闻

*今日国内新闻加载中...*

---

## 💼 财经科技

*今日科技新闻加载中...*

---

## 📊 今日数据

**精选文章：0 篇**

- 🌍 国际: 0 篇
- 🇨🇳 国内: 0 篇
- 💼 科技: 0 篇

---

*Generated by OpenClaw News Aggregator - $(date '+%Y-%m-%d %H:%M:%S')*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
EOF

    echo "✅ Created basic news file structure"
    
    # Try to run the existing fetcher to get actual news
    echo "🔍 Attempting to fetch actual news..."
    if timeout 30 node daily-news-fetcher.js 2>/dev/null; then
        echo "✅ News fetch completed"
        # If the fetcher created output, use it
        if [ -s "latest-news.md" ]; then
            cp latest-news.md "$NEWS_FILE"
            echo "✅ Updated with fetched news"
        fi
    else
        echo "⚠️ News fetch timed out or failed, using basic structure"
    fi
else
    echo "⚠️ No fetcher found, creating basic structure only"
fi

# Git operations
echo "📝 Committing changes to git..."

# Check if there are changes to commit
if git diff --quiet "$NEWS_FILE" 2>/dev/null; then
    echo "ℹ️ No changes to commit"
    exit 0
fi

# Stage and commit
if git add "$NEWS_FILE" && git commit -m "📰 Update daily news for $DATE (basic structure)"; then
    echo "✅ Changes committed successfully"
    
    # Push to remote
    if git push origin master 2>/dev/null; then
        echo "✅ Changes pushed to GitHub"
    else
        echo "⚠️ Push failed - manual intervention may be needed"
        echo "💡 Tip: Run 'git push origin master' manually"
    fi
else
    echo "❌ Failed to commit changes"
    exit 1
fi

echo "✅ Daily news update completed for $DATE"