#!/bin/bash

# Daily News Update Script for follow-builders-digest
# Fetches international, China, and tech news using Tavily API
# Updates the news markdown file for current date and commits to git

set -e

# Configuration
WORK_DIR="/Users/zx/.openclaw/workspace/follow-builders-digest"
SCRIPT_DIR="/Users/zx/.openclaw/workspace/skills/tavily-search"
DATE=$(date +%Y-%m-%d)
NEWS_FILE="$WORK_DIR/2026-$DATE-news.md"

# Change to work directory
cd "$WORK_DIR"

# Function to fetch and format news
fetch_news() {
    local topic="$1"
    local section_title="$2"
    local search_query="$3"
    
    echo "🔍 Fetching $topic news..."
    
    # Use the tavily skill to fetch news
    if [ "$topic" = "international" ]; then
        node "$SCRIPT_DIR/scripts/search.mjs "$search_query" --topic news --days 1" > temp_news.txt
    elif [ "$topic" = "china" ]; then
        node "$SCRIPT_DIR/scripts/search.mjs "$search_query" --topic news --days 1" > temp_news.txt
    elif [ "$topic" = "tech" ]; then
        node "$SCRIPT_DIR/scripts/search.mjs "$search_query" --topic news --days 1" > temp_news.txt
    fi
    
    # Format the news content
    echo "## 📰 $section_title"
    echo ""
    
    if [ -s temp_news.txt ]; then
        # Process and format news results
        sed '1,10d' temp_news.txt | head -20 | while read -r line; do
            if [[ $line == *"Title:"* ]]; then
                title=$(echo "$line" | sed 's/Title: //')
                echo "- **$title**"
            elif [[ $line == *"URL:"* ]]; then
                url=$(echo "$line" | sed 's/URL: //')
                echo "  $url"
                echo ""
            fi
        done
    else
        echo "*暂无新闻数据*"
    fi
    echo ""
}

# Create news file for today
cat > "$NEWS_FILE" << EOF
---
layout: default
title: "新闻速递 — 2026年$DATE"
date: $DATE
---

# 📰 新闻速递 — 2026年$DATE

---

EOF

# Fetch news for each category
fetch_news "international" "🌍 国际新闻" "world news latest breaking news"
echo "---" >> "$NEWS_FILE"
fetch_news "china" "🇨🇳 国内新闻" "China news latest breaking news"
echo "---" >> "$NEWS_FILE"
fetch_news "tech" "💼 财经科技" "AI technology news latest tech news"
echo "---" >> "$NEWS_FILE"

# Add footer
cat >> "$NEWS_FILE" << EOF

## 📊 今日数据

**精选文章：计算中...**

- 🌍 国际: 计算中...
- 🇨🇳 国内: 计算中...
- 💼 科技: 计算中...

---

*Generated by OpenClaw News Aggregator - $(date)*

---

## ⚠️ 数据来源

所有新闻数据均来自 Tavily API 实时搜索结果。
EOF

# Clean up temporary files
rm -f temp_news.txt

# Git operations
echo "📝 Committing changes to git..."
git add "$NEWS_FILE"
git commit -m "📰 Update daily news for $DATE" || echo "No changes to commit"
git push origin main || echo "Push failed or no remote changes"

echo "✅ Daily news update completed for $DATE"